/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/AboutView': RouteRecordInfo<
      '/AboutView',
      '/AboutView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/attendance/[id]': RouteRecordInfo<
      '/attendance/[id]',
      '/attendance/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/DailyReport': RouteRecordInfo<
      '/DailyReport',
      '/DailyReport',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee-shift': RouteRecordInfo<
      '/employee-shift',
      '/employee-shift',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employees': RouteRecordInfo<
      '/employees',
      '/employees',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fingerprintscan': RouteRecordInfo<
      '/fingerprintscan',
      '/fingerprintscan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/HomeView': RouteRecordInfo<
      '/HomeView',
      '/HomeView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/master-times': RouteRecordInfo<
      '/master-times',
      '/master-times',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports': RouteRecordInfo<
      '/reports',
      '/reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/schedule': RouteRecordInfo<
      '/schedule',
      '/schedule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settingtime': RouteRecordInfo<
      '/settingtime',
      '/settingtime',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/timeall': RouteRecordInfo<
      '/timeall',
      '/timeall',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/view-ot': RouteRecordInfo<
      '/view-ot',
      '/view-ot',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/AboutView.vue': {
      routes:
        | '/AboutView'
      views:
        | never
    }
    'src/pages/attendance/[id].vue': {
      routes:
        | '/attendance/[id]'
      views:
        | never
    }
    'src/pages/DailyReport.vue': {
      routes:
        | '/DailyReport'
      views:
        | never
    }
    'src/pages/employee-shift.vue': {
      routes:
        | '/employee-shift'
      views:
        | never
    }
    'src/pages/employees.vue': {
      routes:
        | '/employees'
      views:
        | never
    }
    'src/pages/fingerprintscan.vue': {
      routes:
        | '/fingerprintscan'
      views:
        | never
    }
    'src/pages/HomeView.vue': {
      routes:
        | '/HomeView'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/master-times.vue': {
      routes:
        | '/master-times'
      views:
        | never
    }
    'src/pages/reports.vue': {
      routes:
        | '/reports'
      views:
        | never
    }
    'src/pages/schedule.vue': {
      routes:
        | '/schedule'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/settingtime.vue': {
      routes:
        | '/settingtime'
      views:
        | never
    }
    'src/pages/timeall.vue': {
      routes:
        | '/timeall'
      views:
        | never
    }
    'src/pages/view-ot.vue': {
      routes:
        | '/view-ot'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
