/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/AboutView': RouteRecordInfo<
      '/AboutView',
      '/AboutView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/audit-logs': RouteRecordInfo<
      '/admin/audit-logs',
      '/admin/audit-logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard': RouteRecordInfo<
      '/admin/dashboard',
      '/admin/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/data-management': RouteRecordInfo<
      '/admin/data-management',
      '/admin/data-management',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/employees': RouteRecordInfo<
      '/admin/employees',
      '/admin/employees',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/reports': RouteRecordInfo<
      '/admin/reports',
      '/admin/reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/attendance/[id]': RouteRecordInfo<
      '/attendance/[id]',
      '/attendance/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/DailyReport': RouteRecordInfo<
      '/DailyReport',
      '/DailyReport',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee/edit-profile': RouteRecordInfo<
      '/employee/edit-profile',
      '/employee/edit-profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee/leave-schedule': RouteRecordInfo<
      '/employee/leave-schedule',
      '/employee/leave-schedule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee/profile': RouteRecordInfo<
      '/employee/profile',
      '/employee/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee-leaves-table': RouteRecordInfo<
      '/employee-leaves-table',
      '/employee-leaves-table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee-shift': RouteRecordInfo<
      '/employee-shift',
      '/employee-shift',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employees': RouteRecordInfo<
      '/employees',
      '/employees',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fingerprintscan': RouteRecordInfo<
      '/fingerprintscan',
      '/fingerprintscan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/holidays': RouteRecordInfo<
      '/holidays',
      '/holidays',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/HomeView': RouteRecordInfo<
      '/HomeView',
      '/HomeView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hr/time-correction-approvals': RouteRecordInfo<
      '/hr/time-correction-approvals',
      '/hr/time-correction-approvals',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/leaves/approvals': RouteRecordInfo<
      '/leaves/approvals',
      '/leaves/approvals',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/leaves/request': RouteRecordInfo<
      '/leaves/request',
      '/leaves/request',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/master-times': RouteRecordInfo<
      '/master-times',
      '/master-times',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports': RouteRecordInfo<
      '/reports',
      '/reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/schedule': RouteRecordInfo<
      '/schedule',
      '/schedule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settingtime': RouteRecordInfo<
      '/settingtime',
      '/settingtime',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/time-correction/my-requests': RouteRecordInfo<
      '/time-correction/my-requests',
      '/time-correction/my-requests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/time-correction/request': RouteRecordInfo<
      '/time-correction/request',
      '/time-correction/request',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/timeall': RouteRecordInfo<
      '/timeall',
      '/timeall',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/view-ot': RouteRecordInfo<
      '/view-ot',
      '/view-ot',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/AboutView.vue': {
      routes:
        | '/AboutView'
      views:
        | never
    }
    'src/pages/admin/audit-logs.vue': {
      routes:
        | '/admin/audit-logs'
      views:
        | never
    }
    'src/pages/admin/dashboard.vue': {
      routes:
        | '/admin/dashboard'
      views:
        | never
    }
    'src/pages/admin/data-management.vue': {
      routes:
        | '/admin/data-management'
      views:
        | never
    }
    'src/pages/admin/employees.vue': {
      routes:
        | '/admin/employees'
      views:
        | never
    }
    'src/pages/admin/reports.vue': {
      routes:
        | '/admin/reports'
      views:
        | never
    }
    'src/pages/attendance/[id].vue': {
      routes:
        | '/attendance/[id]'
      views:
        | never
    }
    'src/pages/DailyReport.vue': {
      routes:
        | '/DailyReport'
      views:
        | never
    }
    'src/pages/employee/edit-profile.vue': {
      routes:
        | '/employee/edit-profile'
      views:
        | never
    }
    'src/pages/employee/leave-schedule.vue': {
      routes:
        | '/employee/leave-schedule'
      views:
        | never
    }
    'src/pages/employee/profile.vue': {
      routes:
        | '/employee/profile'
      views:
        | never
    }
    'src/pages/employee-leaves-table.vue': {
      routes:
        | '/employee-leaves-table'
      views:
        | never
    }
    'src/pages/employee-shift.vue': {
      routes:
        | '/employee-shift'
      views:
        | never
    }
    'src/pages/employees.vue': {
      routes:
        | '/employees'
      views:
        | never
    }
    'src/pages/fingerprintscan.vue': {
      routes:
        | '/fingerprintscan'
      views:
        | never
    }
    'src/pages/holidays.vue': {
      routes:
        | '/holidays'
      views:
        | never
    }
    'src/pages/HomeView.vue': {
      routes:
        | '/HomeView'
      views:
        | never
    }
    'src/pages/hr/time-correction-approvals.vue': {
      routes:
        | '/hr/time-correction-approvals'
      views:
        | never
    }
    'src/pages/leaves/approvals.vue': {
      routes:
        | '/leaves/approvals'
      views:
        | never
    }
    'src/pages/leaves/request.vue': {
      routes:
        | '/leaves/request'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/master-times.vue': {
      routes:
        | '/master-times'
      views:
        | never
    }
    'src/pages/reports.vue': {
      routes:
        | '/reports'
      views:
        | never
    }
    'src/pages/schedule.vue': {
      routes:
        | '/schedule'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/settingtime.vue': {
      routes:
        | '/settingtime'
      views:
        | never
    }
    'src/pages/time-correction/my-requests.vue': {
      routes:
        | '/time-correction/my-requests'
      views:
        | never
    }
    'src/pages/time-correction/request.vue': {
      routes:
        | '/time-correction/request'
      views:
        | never
    }
    'src/pages/timeall.vue': {
      routes:
        | '/timeall'
      views:
        | never
    }
    'src/pages/view-ot.vue': {
      routes:
        | '/view-ot'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
