<script setup>
import { ref, computed } from 'vue'

// --- State Management ---
// Filter States
const dateRange = ref('Last 30 Days')
const selectedCategory = ref('All Categories')
const selectedStatus = ref('All Status')

// Mock Data: Filter Options
const dateRanges = ['Today', 'Yesterday', 'Last 7 Days', 'Last 30 Days', 'This Month', 'Last Month', 'Custom']
const categories = ['All Categories', 'Financial', 'HR', 'Operations', 'Inventory']
const statuses = ['All Status', 'Completed', 'Pending', 'Archived', 'Draft']

// Mock Data: Summary Metrics
const metrics = ref([
  {
    title: 'Total Reports',
    value: '1,248',
    trend: '+12%',
    trendColor: 'success',
    icon: 'mdi-file-document-multiple-outline',
    color: 'primary',
    bg: 'blue-lighten-5',
    darkBg: 'rgba(33, 150, 243, 0.1)'
  },
  {
    title: 'Pending Review',
    value: '45',
    trend: '-5%',
    trendColor: 'success',
    icon: 'mdi-clock-time-four-outline',
    color: 'warning',
    bg: 'amber-lighten-5',
    darkBg: 'rgba(255, 193, 7, 0.1)'
  },
  {
    title: 'Generated (PDF)',
    value: '856',
    trend: '+24%',
    trendColor: 'success',
    icon: 'mdi-file-pdf-box',
    color: 'error',
    bg: 'red-lighten-5',
    darkBg: 'rgba(244, 67, 54, 0.1)'
  },
  {
    title: 'System Efficiency',
    value: '98.5%',
    trend: '+0.5%',
    trendColor: 'success',
    icon: 'mdi-server-network',
    color: 'success',
    bg: 'green-lighten-5',
    darkBg: 'rgba(76, 175, 80, 0.1)'
  }
])

// Mock Data: Main Table
const headers = [
  { title: 'Report Name', align: 'start', key: 'name', width: '30%' },
  { title: 'Type', align: 'start', key: 'type' },
  { title: 'Date Generated', align: 'start', key: 'date' },
  { title: 'Generated By', align: 'start', key: 'author' },
  { title: 'Status', align: 'center', key: 'status' },
  { title: 'Actions', align: 'end', key: 'actions', sortable: false }
]

const recentReports = ref([
  { id: 'RPT-001', name: 'Annual Tax Summary 2023', type: 'Financial', date: '2023-10-20', author: 'Sarah Jenkins', status: 'Completed', size: '2.4 MB' },
  { id: 'RPT-002', name: 'Q3 Performance Audit', type: 'HR', date: '2023-10-18', author: 'Marcus Thompson', status: 'Completed', size: '1.1 MB' },
  { id: 'RPT-003', name: 'Safety Compliance Check', type: 'Operations', date: '2023-10-15', author: 'Elena Rodriguez', status: 'Archived', size: '856 KB' },
  { id: 'RPT-004', name: 'Payroll Adjustments Oct', type: 'Financial', date: '2023-10-12', author: 'Sarah Jenkins', status: 'Pending', size: '-' },
  { id: 'RPT-005', name: 'IT Equipment Inventory', type: 'Inventory', date: '2023-10-10', author: 'System Admin', status: 'Completed', size: '3.2 MB' },
  { id: 'RPT-006', name: 'Employee Overtime Log', type: 'HR', date: '2023-10-09', author: 'Marcus Thompson', status: 'Completed', size: '540 KB' },
  { id: 'RPT-007', name: 'Server Uptime Report', type: 'Operations', date: '2023-10-08', author: 'System Bot', status: 'Completed', size: '120 KB' },
])

// Actions
const refreshData = () => {
  console.log('Refreshing data...')
}

const printReport = () => {
  window.print()
}
</script>

<template>
  <v-container fluid class="pa-4 pa-md-6 pa-lg-8 d-flex flex-column h-screen-custom bg-background">

    <!-- Top Bar: Header & Actions -->
    <div class="d-flex flex-column flex-md-row justify-space-between align-md-center mb-6 gap-4">
      <div>
        <h1 class="text-h4 font-weight-bold text-high-emphasis">Reports Center</h1>
        <div class="d-flex align-center text-subtitle-2 text-medium-emphasis mt-1">
          <span>Overview</span>
          <v-icon icon="mdi-chevron-right" size="small" class="mx-1"></v-icon>
          <span class="text-primary font-weight-medium">All Reports</span>
        </div>
      </div>

      <div class="d-flex align-center gap-3 actions-wrapper">
        <v-btn
          color="surface"
          variant="outlined"
          class="text-none font-weight-bold border-opacity-75"
          prepend-icon="mdi-refresh"
          height="40"
          rounded="lg"
          @click="refreshData"
        >
          Refresh
        </v-btn>

        <v-btn
          color="surface"
          variant="outlined"
          class="text-none font-weight-bold border-opacity-75"
          prepend-icon="mdi-printer-outline"
          height="40"
          rounded="lg"
          @click="printReport"
        >
          Print
        </v-btn>

        <v-menu location="bottom end">
          <template v-slot:activator="{ props }">
            <v-btn
              v-bind="props"
              color="primary"
              variant="flat"
              class="text-none font-weight-bold"
              prepend-icon="mdi-tray-arrow-down"
              append-icon="mdi-chevron-down"
              height="40"
              elevation="2"
              rounded="lg"
            >
              Export
            </v-btn>
          </template>
          <v-list density="compact" rounded="lg" elevation="4" class="mt-2 py-2">
            <v-list-item value="pdf" prepend-icon="mdi-file-pdf-box" title="Export as PDF"></v-list-item>
            <v-list-item value="excel" prepend-icon="mdi-file-excel" title="Export as Excel"></v-list-item>
            <v-list-item value="csv" prepend-icon="mdi-file-delimited" title="Export as CSV"></v-list-item>
          </v-list>
        </v-menu>
      </div>
    </div>

    <!-- Metrics Section -->
    <v-row class="mb-6 flex-grow-0">
      <v-col cols="12" sm="6" lg="3" v-for="(metric, i) in metrics" :key="i">
        <v-card flat rounded="xl" class="pa-5 border glass-card h-100 hover-elevate">
          <div class="d-flex justify-space-between align-start mb-4">
            <v-avatar
              :color="metric.color"
              variant="flat"
              rounded="lg"
              size="48"
              class="elevation-2"
            >
              <v-icon :icon="metric.icon" size="24" color="white"></v-icon>
            </v-avatar>
            <v-chip
              size="small"
              :color="metric.trendColor"
              variant="tonal"
              class="font-weight-bold px-2"
              prepend-icon="mdi-trending-up"
            >
              {{ metric.trend }}
            </v-chip>
          </div>
          <div class="mt-auto">
            <h3 class="text-h4 font-weight-bold text-high-emphasis mb-0">{{ metric.value }}</h3>
            <p class="text-body-2 text-medium-emphasis">{{ metric.title }}</p>
          </div>
        </v-card>
      </v-col>
    </v-row>

    <!-- Main Content: Filters & Data Table -->
    <v-card flat rounded="xl" class="flex-grow-1 d-flex flex-column border glass-card overflow-hidden">
      <!-- Toolbar Filters -->
      <div class="px-6 py-4 border-b d-flex flex-column flex-lg-row align-start align-lg-center justify-space-between gap-4 bg-surface-lighten-1">

        <!-- Left Filters -->
        <div class="d-flex flex-wrap align-center gap-3 w-100 w-lg-auto">
          <div class="filter-group">
            <v-select
              v-model="dateRange"
              :items="dateRanges"
              density="compact"
              variant="outlined"
              hide-details
              rounded="lg"
              bg-color="surface"
              class="filter-select font-weight-medium"
              prepend-inner-icon="mdi-calendar-range"
              flat
            ></v-select>
          </div>
          <div class="filter-group">
             <v-select
              v-model="selectedCategory"
              :items="categories"
              density="compact"
              variant="outlined"
              hide-details
              rounded="lg"
              bg-color="surface"
              class="filter-select font-weight-medium"
              prepend-inner-icon="mdi-shape-outline"
              flat
            ></v-select>
          </div>
           <div class="filter-group">
             <v-select
              v-model="selectedStatus"
              :items="statuses"
              density="compact"
              variant="outlined"
              hide-details
              rounded="lg"
              bg-color="surface"
              class="filter-select font-weight-medium"
              prepend-inner-icon="mdi-list-status"
              flat
            ></v-select>
          </div>
        </div>

        <!-- Search -->
        <div class="w-100 w-lg-auto" style="min-width: 250px;">
           <v-text-field
            placeholder="Search reports..."
            density="compact"
            variant="outlined"
            hide-details
            rounded="lg"
            bg-color="surface"
            prepend-inner-icon="mdi-magnify"
            flat
          ></v-text-field>
        </div>
      </div>

      <!-- Data Table -->
      <v-data-table
        :headers="headers"
        :items="recentReports"
        class="flex-grow-1 bg-transparent"
        fixed-header
        hover
      >
        <!-- Custom Formatting -->
        <template v-slot:item.name="{ item }">
          <div class="d-flex align-center py-2">
            <v-avatar color="primary" variant="tonal" rounded="lg" size="36" class="mr-3">
              <span class="text-caption font-weight-bold">{{ item.type.substring(0,2).toUpperCase() }}</span>
            </v-avatar>
            <div>
              <div class="text-subtitle-2 font-weight-bold text-high-emphasis">{{ item.name }}</div>
              <div class="text-caption text-medium-emphasis">{{ item.size }} • {{ item.author }}</div>
            </div>
          </div>
        </template>

        <template v-slot:item.type="{ item }">
           <span class="text-body-2 font-weight-medium text-high-emphasis">{{ item.type }}</span>
        </template>

        <template v-slot:item.status="{ item }">
          <v-chip
            size="small"
            rounded="lg"
            :color="item.status === 'Completed' ? 'success' : item.status === 'Pending' ? 'warning' : 'grey'"
            :variant="item.status === 'Pending' ? 'outlined' : 'flat'"
            class="font-weight-bold text-uppercase px-3"
            style="letter-spacing: 0.5px; font-size: 10px; height: 24px;"
          >
            {{ item.status }}
          </v-chip>
        </template>

         <template v-slot:item.actions="{ item }">
          <div class="d-flex justify-end gap-1">
             <v-btn icon="mdi-download" variant="text" density="comfortable" size="small" color="primary"></v-btn>
             <v-btn icon="mdi-dots-vertical" variant="text" density="comfortable" size="small" color="medium-emphasis"></v-btn>
          </div>
        </template>

        <template v-slot:bottom>
           <!-- Custom Footer if needed, or default pagination -->
           <div class="pa-4 border-t d-flex align-center justify-end">
              <v-pagination :length="3" density="comfortable" rounded="circle" active-color="primary" size="small"></v-pagination>
           </div>
        </template>
      </v-data-table>
    </v-card>

  </v-container>
</template>

<style scoped>
.h-screen-custom {
  /* Use viewport height minus standard navbar height if present, else 100vh */
  height: calc(100vh - 64px);
  max-height: 100vh;
  overflow-y: hidden; /* Prevent body scroll */
}

.glass-card {
  backdrop-filter: blur(12px);
  background: rgba(var(--v-theme-surface), 0.95) !important;
  /* Subtle border handling via props or class */
}

.gap-3 { gap: 12px; }
.gap-4 { gap: 16px; }

.hover-elevate {
  transition: transform 0.2s cubic-bezier(0.4, 0, 0.2, 1), box-shadow 0.2s;
}
.hover-elevate:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0,0,0,0.08) !important;
}

.filter-select {
  width: 160px;
}

@media (max-width: 960px) {
  .h-screen-custom {
    height: auto !important;
    overflow-y: auto !important;
    padding-bottom: 80px; /* Space for mobile nav if needed */
  }

  .filter-select {
     width: 100%;
     flex: 1 1 auto;
  }

  .filter-group {
    width: 48%; /* 2 columns on mobile */
    flex-grow: 1;
  }

  .actions-wrapper {
    width: 100%;
    justify-content: flex-end;
  }
}
</style>
